### PR TITLE
Add configuration.json

### PR DESCRIPTION
**Pull request by allaway**
Added json file to configure the manifest name mapping in the app, can obviously be used for other configuration elements too :)

### CODE REVIEW

**Comment by allaway** [comment]
I tested this on my end and it seemed to work fine but would appreciate an independent test. 

I added a "type" concept to the mapping dataframe to allow the filtering by "assay" that happens on L509 of app.R.

**Comment by milen-sage** [comment]
Looping in @xdoan

**Comment by allaway** [comment]
Oops, sorry, some late night commits to the wrong branch made this un-ready for review.

**Comment by allaway** [comment]
OK, this should be ready for review again.

**Comment by xdoan** [comment]
will be testing!

**Review by xdoan — APPROVED** [review]

**Pull request merged**
